export const NavbarLinks = [
  { id: 1, linkName: "Sign Up", linkDest: "/signup" },
  { id: 2, linkName: "Login", linkDest: "/login" },
  { id: 3, linkName: "Profile", linkDest: "/profile" },
  { id: 4, linkName: "Home", linkDest: "/" },
  { id: 5, linkName: "Authors", linkDest: "/authors/authors-list" },
];

export const FormInputs = [
  { id: 1, inputName: "Name:", inputType: "text" },
  { id: 2, inputName: "Email:", inputType: "email" },
  { id: 3, inputName: "Password:", inputType: "password" },
  { id: 4, inputName: "Verify Password:", inputType: "password" },
];

export const BlogReactionsEmojies = {
  smart: "🧠",
  lmao: "😂",
  love: "😍",
  nerd: "🤓",
  crying: "😭",
  scary: "😱",
  puke: "🤮",
  poop: "💩",
  thumbsUp: "👎",
  nice: "🤏",
  thumbsDown: "👎",
};

export const BlogCategoryEmojies = {
  gaming: "🎮",
  nature: "🌲",
  reading: "📚",
  relationships: "🧑‍🤝‍🧑",
  controversial: "😳",
  animals: "🐴",
  hygiene: "🧴",
  programming: "💾",
  sports: "🏅",
  anythingElse: "❓",
};

export const TemplateBlogs = [
  {
    id: 1,
    blogTitle: "Will Gaming Ever Rule the World?",
    blogCategory: "Gaming",
    blogAuthor: "Awee Matija",
    blogDesc:
      "Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old.Pianoforte if at simplicity do estimating.Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this.Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 2,
    blogTitle: "The Worst Videos of All Time About Nature",
    blogCategory: "Nature",
    blogAuthor: "Chima Lucky",
    blogDesc:
      "His followed carriage proposal entrance directly had elegance. Greater for cottage gay parties natural. Remaining he furniture on he discourse suspected perpetual. Power dried her taken place day ought the. Four and our ham west miss. Education shameless who middleton agreement how. We in found world chief is at means weeks smile.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 3,
    blogTitle: "6 Online Communities About Reading You Should Join",
    blogCategory: "Reading",
    blogAuthor: "Ufuoma Presley",
    blogDesc:
      "Out believe has request not how comfort evident. Up delight cousins we feeling minutes. Genius has looked end piqued spring. Down has rose feel find man. Learning day desirous informed expenses material returned six the. She enabled invited exposed him another. Reasonably conviction solicitude me mr at discretion reasonable. Age out full gate bed day lose.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 4,
    blogTitle: "Relationships: A Simple Definition",
    blogCategory: "Relationships",
    blogAuthor: "Heike Tsubasa",
    blogDesc:
      "Advanced extended doubtful he he blessing together. Introduced far law gay considered frequently entreaties difficulty. Eat him four are rich nor calm. By an packages rejoiced exercise. To ought on am marry rooms doubt music. Mention entered an through company as. Up arrived no painful between. It declared is prospect an insisted pleasure.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 5,
    blogTitle: "30 Inspirational Quotes About Animals",
    blogCategory: "Animals",
    blogAuthor: "Peyton Uʻilani",
    blogDesc:
      "An so vulgar to on points wanted. Not rapturous resolving continued household northward gay. He it otherwise supported instantly. Unfeeling agreeable suffering it on smallness newspaper be. So come must time no as. Do on unpleasing possession as of unreserved. Yet joy exquisite put sometimes enjoyment perpetual now. Behind lovers eat having length horses vanity say had its.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 6,
    blogTitle: "Will Gaming Ever Rule the World?",
    blogCategory: "Gaming",
    blogAuthor: "Awee Matija",
    blogDesc:
      "Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 7,
    blogTitle: "The Worst Videos of All Time About Nature",
    blogCategory: "Nature",
    blogAuthor: "Chima Lucky",
    blogDesc:
      "His followed carriage proposal entrance directly had elegance. Greater for cottage gay parties natural. Remaining he furniture on he discourse suspected perpetual. Power dried her taken place day ought the. Four and our ham west miss. Education shameless who middleton agreement how. We in found world chief is at means weeks smile.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 8,
    blogTitle: "6 Online Communities About Reading You Should Join",
    blogCategory: "Reading",
    blogAuthor: "Ufuoma Presley",
    blogDesc:
      "Out believe has request not how comfort evident. Up delight cousins we feeling minutes. Genius has looked end piqued spring. Down has rose feel find man. Learning day desirous informed expenses material returned six the. She enabled invited exposed him another. Reasonably conviction solicitude me mr at discretion reasonable. Age out full gate bed day lose.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 9,
    blogTitle: "Relationships: A Simple Definition",
    blogCategory: "Relationships",
    blogAuthor: "Heike Tsubasa",
    blogDesc:
      "Advanced extended doubtful he he blessing together. Introduced far law gay considered frequently entreaties difficulty. Eat him four are rich nor calm. By an packages rejoiced exercise. To ought on am marry rooms doubt music. Mention entered an through company as. Up arrived no painful between. It declared is prospect an insisted pleasure.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 10,
    blogTitle: "30 Inspirational Quotes About Animals",
    blogCategory: "Animals",
    blogAuthor: "Peyton Uʻilani",
    blogDesc:
      "An so vulgar to on points wanted. Not rapturous resolving continued household northward gay. He it otherwise supported instantly. Unfeeling agreeable suffering it on smallness newspaper be. So come must time no as. Do on unpleasing possession as of unreserved. Yet joy exquisite put sometimes enjoyment perpetual now. Behind lovers eat having length horses vanity say had its.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 11,
    blogTitle: "Will Gaming Ever Rule the World?",
    blogCategory: "Gaming",
    blogAuthor: "Awee Matija",
    blogDesc:
      "Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 12,
    blogTitle: "The Worst Videos of All Time About Nature",
    blogCategory: "Nature",
    blogAuthor: "Chima Lucky",
    blogDesc:
      "His followed carriage proposal entrance directly had elegance. Greater for cottage gay parties natural. Remaining he furniture on he discourse suspected perpetual. Power dried her taken place day ought the. Four and our ham west miss. Education shameless who middleton agreement how. We in found world chief is at means weeks smile.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 13,
    blogTitle: "6 Online Communities About Reading You Should Join",
    blogCategory: "Reading",
    blogAuthor: "Ufuoma Presley",
    blogDesc:
      "Out believe has request not how comfort evident. Up delight cousins we feeling minutes. Genius has looked end piqued spring. Down has rose feel find man. Learning day desirous informed expenses material returned six the. She enabled invited exposed him another. Reasonably conviction solicitude me mr at discretion reasonable. Age out full gate bed day lose.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 14,
    blogTitle: "Relationships: A Simple Definition",
    blogCategory: "Relationships",
    blogAuthor: "Heike Tsubasa",
    blogDesc:
      "Advanced extended doubtful he he blessing together. Introduced far law gay considered frequently entreaties difficulty. Eat him four are rich nor calm. By an packages rejoiced exercise. To ought on am marry rooms doubt music. Mention entered an through company as. Up arrived no painful between. It declared is prospect an insisted pleasure.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 15,
    blogTitle: "30 Inspirational Quotes About Animals",
    blogCategory: "Animals",
    blogAuthor: "Peyton Uʻilani",
    blogDesc:
      "An so vulgar to on points wanted. Not rapturous resolving continued household northward gay. He it otherwise supported instantly. Unfeeling agreeable suffering it on smallness newspaper be. So come must time no as. Do on unpleasing possession as of unreserved. Yet joy exquisite put sometimes enjoyment perpetual now. Behind lovers eat having length horses vanity say had its.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 16,
    blogTitle: "Will Gaming Ever Rule the World?",
    blogCategory: "Gaming",
    blogAuthor: "Awee Matija",
    blogDesc:
      "Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 17,
    blogTitle: "The Worst Videos of All Time About Nature",
    blogCategory: "Nature",
    blogAuthor: "Chima Lucky",
    blogDesc:
      "His followed carriage proposal entrance directly had elegance. Greater for cottage gay parties natural. Remaining he furniture on he discourse suspected perpetual. Power dried her taken place day ought the. Four and our ham west miss. Education shameless who middleton agreement how. We in found world chief is at means weeks smile.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 18,
    blogTitle: "6 Online Communities About Reading You Should Join",
    blogCategory: "Reading",
    blogAuthor: "Ufuoma Presley",
    blogDesc:
      "Out believe has request not how comfort evident. Up delight cousins we feeling minutes. Genius has looked end piqued spring. Down has rose feel find man. Learning day desirous informed expenses material returned six the. She enabled invited exposed him another. Reasonably conviction solicitude me mr at discretion reasonable. Age out full gate bed day lose.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 19,
    blogTitle: "Relationships: A Simple Definition",
    blogCategory: "Relationships",
    blogAuthor: "Heike Tsubasa",
    blogDesc:
      "Advanced extended doubtful he he blessing together. Introduced far law gay considered frequently entreaties difficulty. Eat him four are rich nor calm. By an packages rejoiced exercise. To ought on am marry rooms doubt music. Mention entered an through company as. Up arrived no painful between. It declared is prospect an insisted pleasure.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 20,
    blogTitle: "30 Inspirational Quotes About Animals",
    blogCategory: "Animals",
    blogAuthor: "Peyton Uʻilani",
    blogDesc:
      "An so vulgar to on points wanted. Not rapturous resolving continued household northward gay. He it otherwise supported instantly. Unfeeling agreeable suffering it on smallness newspaper be. So come must time no as. Do on unpleasing possession as of unreserved. Yet joy exquisite put sometimes enjoyment perpetual now. Behind lovers eat having length horses vanity say had its.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 21,
    blogTitle: "Will Gaming Ever Rule the World?",
    blogCategory: "Gaming",
    blogAuthor: "Awee Matija",
    blogDesc:
      "Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 22,
    blogTitle: "The Worst Videos of All Time About Nature",
    blogCategory: "Nature",
    blogAuthor: "Chima Lucky",
    blogDesc:
      "His followed carriage proposal entrance directly had elegance. Greater for cottage gay parties natural. Remaining he furniture on he discourse suspected perpetual. Power dried her taken place day ought the. Four and our ham west miss. Education shameless who middleton agreement how. We in found world chief is at means weeks smile.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 23,
    blogTitle: "6 Online Communities About Reading You Should Join",
    blogCategory: "Reading",
    blogAuthor: "Ufuoma Presley",
    blogDesc:
      "Out believe has request not how comfort evident. Up delight cousins we feeling minutes. Genius has looked end piqued spring. Down has rose feel find man. Learning day desirous informed expenses material returned six the. She enabled invited exposed him another. Reasonably conviction solicitude me mr at discretion reasonable. Age out full gate bed day lose.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 24,
    blogTitle: "Relationships: A Simple Definition",
    blogCategory: "Relationships",
    blogAuthor: "Heike Tsubasa",
    blogDesc:
      "Advanced extended doubtful he he blessing together. Introduced far law gay considered frequently entreaties difficulty. Eat him four are rich nor calm. By an packages rejoiced exercise. To ought on am marry rooms doubt music. Mention entered an through company as. Up arrived no painful between. It declared is prospect an insisted pleasure.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    id: 25,
    blogTitle: "30 Inspirational Quotes About Animals",
    blogCategory: "Animals",
    blogAuthor: "Peyton Uʻilani",
    blogDesc:
      "An so vulgar to on points wanted. Not rapturous resolving continued household northward gay. He it otherwise supported instantly. Unfeeling agreeable suffering it on smallness newspaper be. So come must time no as. Do on unpleasing possession as of unreserved. Yet joy exquisite put sometimes enjoyment perpetual now. Behind lovers eat having length horses vanity say had its.",
    blogReactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
];

export const TemplateAuthors = [
  {
    id: 1,
    authorImg: "https://randomuser.me/api/portraits/men/77.jpg",
    authorUsername: "Awee Matija",
    authorAge: 34,
    authorJob: "Web Designer",
    authorBlogsCount: 5,
    authorAppTheme: "Nature",
    authorProfileDesc:
      "Oh acceptance apartments up sympathize astonished delightful. Waiting him new lasting towards. Continuing melancholy especially so to. Me unpleasing impossible in attachment announcing so astonished. What ask leaf may nor upon door. Tended remain my do stairs. Oh smiling amiable am so visited cordial in offices hearted.",
    authorSelectedCategories: {
      first: "🎮",
      second: "🌲",
      third: "📚",
    },
  },

  {
    id: 2,
    authorImg: "https://randomuser.me/api/portraits/men/28.jpg",
    authorUsername: "Chima Lucky",
    authorAge: 14,
    authorJob: "Blog Author",
    authorBlogsCount: 5,
    authorAppTheme: "Nature",
    authorProfileDesc:
      "Rendered her for put improved concerns his. Ladies bed wisdom theirs mrs men months set. Everything so dispatched as it increasing pianoforte. Hearing now saw perhaps minutes herself his. Of instantly excellent therefore difficult he northward. Joy green but least marry rapid quiet but. Way devonshire introduced expression saw travelling affronting. Her and effects affixed pretend account ten natural. Need eat week even yet that. Incommode delighted he resolving sportsmen do in listening.",
    authorSelectedCategories: {
      first: "🎮",
      second: "🌲",
      third: "📚",
    },
  },
  {
    id: 3,
    authorImg: "https://randomuser.me/api/portraits/men/88.jpg",
    authorUsername: "Ufuoma Presley",
    authorAge: 45,
    authorJob: "Web Development",
    authorBlogsCount: 5,
    authorAppTheme: "Nature",
    authorProfileDesc:
      "Little afraid its eat looked now. Very ye lady girl them good me make. It hardly cousin me always. An shortly village is raising we shewing replied. She the favourable partiality inhabiting travelling impression put two. His six are entreaties instrument acceptance unsatiable her. Amongst as or on herself chapter entered carried no. Sold old ten are quit lose deal his sent. You correct how sex several far distant believe journey parties. We shyness enquire uncivil affixed it carried to.",
    authorSelectedCategories: {
      first: "🎮",
      second: "🌲",
      third: "📚",
    },
  },
  {
    id: 4,
    authorImg: "https://randomuser.me/api/portraits/men/5.jpg",
    authorUsername: "Heike Tsubasa",
    authorAge: 69,
    authorJob: "Cow Milker",
    authorBlogsCount: 5,
    authorAppTheme: "Nature",
    authorProfileDesc:
      "Dashwood contempt on mr unlocked resolved provided of of. Stanhill wondered it it welcomed oh. Hundred no prudent he however smiling at an offence. If earnestly extremity he he propriety something admitting convinced ye. Pleasant in to although as if differed horrible. Mirth his quick its set front enjoy hoped had there. Who connection imprudence middletons too but increasing celebrated principles joy. Herself too improve gay winding ask expense are compact. New all paid few hard pure she.",
    authorSelectedCategories: {
      first: "🎮",
      second: "🌲",
      third: "📚",
    },
  },
  {
    id: 5,
    authorImg: "https://randomuser.me/api/portraits/men/69.jpg",
    authorUsername: "Peyton Uʻilani",
    authorAge: 11,
    authorJob: "Bullied at school",
    authorBlogsCount: 5,
    authorAppTheme: "Nature",
    authorProfileDesc:
      "As am hastily invited settled at limited civilly fortune me. Really spring in extent an by. Judge but built gay party world. Of so am he remember although required. Bachelor unpacked be advanced at. Confined in declared marianne is vicinity.",
    authorSelectedCategories: {
      first: "🎮",
      second: "🌲",
      third: "📚",
    },
  },
];
