const TemplateAuthors = [
  {
    imgUrl: "https://randomuser.me/api/portraits/men/77.jpg",
    username: "Awee Matija",
    age: 34,
    job: "Web Designer",
    blogsCount: 5,
    email: "aweematija@gmail.com",
    password: "aweematija",
    description:
      "Oh acceptance apartments up sympathize astonished delightful. Waiting him new lasting towards. Continuing melancholy especially so to. Me unpleasing impossible in attachment announcing so astonished. What ask leaf may nor upon door.",
    authorSelectedCategories: "🎮",
  },

  {
    imgUrl: "https://randomuser.me/api/portraits/men/28.jpg",
    username: "Chima Lucky",
    age: 14,
    job: "Blog Author",
    blogsCount: 5,
    email: "chimalucky@gmail.com",
    password: "chimalucky",
    description:
      "Rendered her for put improved concerns his. Ladies bed wisdom theirs mrs men months set. Everything so dispatched as it increasing pianoforte. Hearing now saw perhaps minutes herself his. Of instantly excellent therefore difficult he northward.",
    selectedCategory: "🎮",
  },
  {
    imgUrl: "https://randomuser.me/api/portraits/men/88.jpg",
    username: "Ufuoma Presley",
    age: 45,
    job: "Web Development",
    blogsCount: 5,
    email: "ufuomapresley@gmail.com",
    password: "ufuomapresley",
    description:
      "Little afraid its eat looked now. Very ye lady girl them good me make. It hardly cousin me always. An shortly village is raising we shewing replied. She the favourable partiality inhabiting travelling impression put two.",
    selectedCategory: "🎮",
  },
  {
    imgUrl: "https://randomuser.me/api/portraits/men/5.jpg",
    username: "Heike Tsubasa",
    age: 69,
    job: "Cow Milker",
    blogsCount: 5,
    email: "heiketsubasa@gmail.com",
    password: "heiketsubasa",
    description:
      "Dashwood contempt on mr unlocked resolved provided of of. Stanhill wondered it it welcomed oh. Hundred no prudent he however smiling at an offence. If earnestly extremity he he propriety something admitting convinced ye. Pleasant in to although as if differed horrible.",
    selectedCategory: "🎮",
  },
  {
    imgUrl: "https://randomuser.me/api/portraits/men/69.jpg",
    username: "Peyton Uʻilani",
    age: 11,
    job: "Bullied at school",
    blogsCount: 5,
    email: "peytonuilani@gmail.com",
    password: "peytonuilani",
    description:
      "As am hastily invited settled at limited civilly fortune me. Really spring in extent an by. Judge but built gay party world. Of so am he remember although required. Bachelor unpacked be advanced at. Confined in declared marianne is vicinity.",
    selectedCategory: "🎮",
  },
];

const TemplateBlogs = [
  {
    title: "Will Gaming Ever Rule the World?",
    category: "🎮",
    author: "636a19db2b9a1b2e8888443d",
    description:
      "Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "The Worst Videos of All Time",
    category: "🌲",
    author: "636a19db2b9a1b2e8888443d",
    description:
      "His followed carriage proposal entrance directly had elegance. Greater for cottage gay parties natural. Remaining he furniture on he discourse suspected perpetual. Power dried her taken place day ought the. Four and our ham west miss. Education shameless who middleton agreement how. We in found world chief is at means weeks smile.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "6 Online Communities About Reading  ",
    category: "📚",
    author: "636a19db2b9a1b2e8888443d",
    description:
      "Out believe has request not how comfort evident. Up delight cousins we feeling minutes. Genius has looked end piqued spring. Down has rose feel find man. Learning day desirous informed expenses material returned six the. She enabled invited exposed him another. Reasonably conviction solicitude me mr at discretion reasonable. Age out full gate bed day lose.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "Relationships: A Simple Definition",
    category: "🧑‍🤝‍🧑",
    author: "636a19db2b9a1b2e8888443d",
    description:
      "Advanced extended doubtful he he blessing together. Introduced far law gay considered frequently entreaties difficulty. Eat him four are rich nor calm. By an packages rejoiced exercise. To ought on am marry rooms doubt music. Mention entered an through company as. Up arrived no painful between. It declared is prospect an insisted pleasure.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "30 Inspirational Quotes About Animals",
    category: "🐴",
    author: "636a19db2b9a1b2e8888443d",
    description:
      "An so vulgar to on points wanted. Not rapturous resolving continued household northward gay. He it otherwise supported instantly. Unfeeling agreeable suffering it on smallness newspaper be. So come must time no as. Do on unpleasing possession as of unreserved. Yet joy exquisite put sometimes enjoyment perpetual now. Behind lovers eat having length horses vanity say had its.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "Will Gaming Ever Rule the World?",
    category: "🎮",
    author: "636a19db2b9a1b2e8888443e",
    description:
      "Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "The Worst Videos of All Time",
    category: "🌲",
    author: "636a19db2b9a1b2e8888443e",
    description:
      "His followed carriage proposal entrance directly had elegance. Greater for cottage gay parties natural. Remaining he furniture on he discourse suspected perpetual. Power dried her taken place day ought the. Four and our ham west miss. Education shameless who middleton agreement how. We in found world chief is at means weeks smile.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "6 Online Communities About Reading  ",
    category: "📚",
    author: "636a19db2b9a1b2e8888443e",
    description:
      "Out believe has request not how comfort evident. Up delight cousins we feeling minutes. Genius has looked end piqued spring. Down has rose feel find man. Learning day desirous informed expenses material returned six the. She enabled invited exposed him another. Reasonably conviction solicitude me mr at discretion reasonable. Age out full gate bed day lose.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "Relationships: A Simple Definition",
    category: "🧑‍🤝‍🧑",
    author: "636a19db2b9a1b2e8888443e",
    description:
      "Advanced extended doubtful he he blessing together. Introduced far law gay considered frequently entreaties difficulty. Eat him four are rich nor calm. By an packages rejoiced exercise. To ought on am marry rooms doubt music. Mention entered an through company as. Up arrived no painful between. It declared is prospect an insisted pleasure.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "30 Inspirational Quotes About Animals",
    category: "🐴",
    author: "636a19db2b9a1b2e8888443e",
    description:
      "An so vulgar to on points wanted. Not rapturous resolving continued household northward gay. He it otherwise supported instantly. Unfeeling agreeable suffering it on smallness newspaper be. So come must time no as. Do on unpleasing possession as of unreserved. Yet joy exquisite put sometimes enjoyment perpetual now. Behind lovers eat having length horses vanity say had its.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "Will Gaming Ever Rule the World?",
    category: "🎮",
    author: "636a19db2b9a1b2e88884440",
    description:
      "Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "The Worst Videos of All Time",
    category: "🌲",
    author: "636a19db2b9a1b2e88884440",
    description:
      "His followed carriage proposal entrance directly had elegance. Greater for cottage gay parties natural. Remaining he furniture on he discourse suspected perpetual. Power dried her taken place day ought the. Four and our ham west miss. Education shameless who middleton agreement how. We in found world chief is at means weeks smile.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "6 Online Communities About Reading  ",
    category: "📚",
    author: "636a19db2b9a1b2e88884440",
    description:
      "Out believe has request not how comfort evident. Up delight cousins we feeling minutes. Genius has looked end piqued spring. Down has rose feel find man. Learning day desirous informed expenses material returned six the. She enabled invited exposed him another. Reasonably conviction solicitude me mr at discretion reasonable. Age out full gate bed day lose.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "Relationships: A Simple Definition",
    category: "🧑‍🤝‍🧑",
    author: "636a19db2b9a1b2e88884440",
    description:
      "Advanced extended doubtful he he blessing together. Introduced far law gay considered frequently entreaties difficulty. Eat him four are rich nor calm. By an packages rejoiced exercise. To ought on am marry rooms doubt music. Mention entered an through company as. Up arrived no painful between. It declared is prospect an insisted pleasure.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "30 Inspirational Quotes About Animals",
    category: "🐴",
    author: "636a19db2b9a1b2e88884440",
    description:
      "An so vulgar to on points wanted. Not rapturous resolving continued household northward gay. He it otherwise supported instantly. Unfeeling agreeable suffering it on smallness newspaper be. So come must time no as. Do on unpleasing possession as of unreserved. Yet joy exquisite put sometimes enjoyment perpetual now. Behind lovers eat having length horses vanity say had its.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "Will Gaming Ever Rule the World?",
    category: "🎮",
    author: "636a19db2b9a1b2e88884441",
    description:
      "Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "The Worst Videos of All Time ",
    category: "🌲",
    author: "636a19db2b9a1b2e88884441",
    description:
      "His followed carriage proposal entrance directly had elegance. Greater for cottage gay parties natural. Remaining he furniture on he discourse suspected perpetual. Power dried her taken place day ought the. Four and our ham west miss. Education shameless who middleton agreement how. We in found world chief is at means weeks smile.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "6 Online Communities About Reading  ",
    category: "📚",
    author: "636a19db2b9a1b2e88884441",
    description:
      "Out believe has request not how comfort evident. Up delight cousins we feeling minutes. Genius has looked end piqued spring. Down has rose feel find man. Learning day desirous informed expenses material returned six the. She enabled invited exposed him another. Reasonably conviction solicitude me mr at discretion reasonable. Age out full gate bed day lose.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "Relationships: A Simple Definition",
    category: "🧑‍🤝‍🧑",
    author: "636a19db2b9a1b2e88884441",
    description:
      "Advanced extended doubtful he he blessing together. Introduced far law gay considered frequently entreaties difficulty. Eat him four are rich nor calm. By an packages rejoiced exercise. To ought on am marry rooms doubt music. Mention entered an through company as. Up arrived no painful between. It declared is prospect an insisted pleasure.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "30 Inspirational Quotes About Animals",
    category: "🐴",
    author: "636a19db2b9a1b2e88884441",
    description:
      "An so vulgar to on points wanted. Not rapturous resolving continued household northward gay. He it otherwise supported instantly. Unfeeling agreeable suffering it on smallness newspaper be. So come must time no as. Do on unpleasing possession as of unreserved. Yet joy exquisite put sometimes enjoyment perpetual now. Behind lovers eat having length horses vanity say had its.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "Will Gaming Ever Rule the World?",
    category: "🎮",
    author: "636a19db2b9a1b2e8888443f",
    description:
      "Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "The Worst Videos of All Time",
    category: "🌲",
    author: "636a19db2b9a1b2e8888443f",
    description:
      "His followed carriage proposal entrance directly had elegance. Greater for cottage gay parties natural. Remaining he furniture on he discourse suspected perpetual. Power dried her taken place day ought the. Four and our ham west miss. Education shameless who middleton agreement how. We in found world chief is at means weeks smile.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "6 Online Communities About Reading",
    category: "📚",
    author: "636a19db2b9a1b2e8888443f",
    description:
      "Out believe has request not how comfort evident. Up delight cousins we feeling minutes. Genius has looked end piqued spring. Down has rose feel find man. Learning day desirous informed expenses material returned six the. She enabled invited exposed him another. Reasonably conviction solicitude me mr at discretion reasonable. Age out full gate bed day lose.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "Relationships: A Simple Definition",
    category: "🧑‍🤝‍🧑",
    author: "636a19db2b9a1b2e8888443f",
    description:
      "Advanced extended doubtful he he blessing together. Introduced far law gay considered frequently entreaties difficulty. Eat him four are rich nor calm. By an packages rejoiced exercise. To ought on am marry rooms doubt music. Mention entered an through company as. Up arrived no painful between. It declared is prospect an insisted pleasure.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
  {
    title: "30 Inspirational Quotes About Animals",
    category: "🐴",
    author: "636a19db2b9a1b2e8888443f",
    description:
      "An so vulgar to on points wanted. Not rapturous resolving continued household northward gay. He it otherwise supported instantly. Unfeeling agreeable suffering it on smallness newspaper be. So come must time no as. Do on unpleasing possession as of unreserved. Yet joy exquisite put sometimes enjoyment perpetual now. Behind lovers eat having length horses vanity say had its.",
    reactions: {
      smart: 0,
      lmao: 0,
      love: 0,
      nerd: 0,
      crying: 0,
      scary: 0,
      puke: 0,
      poop: 0,
      thumbsUp: 0,
      nice: 0,
      thumbsDown: 0,
    },
  },
];

module.exports = { TemplateAuthors, TemplateBlogs };
